#!/bin/bash

set -o pipefail
export PATH=/bin

case "$1" in
  start | "")
    hostname anansi

    if [[ $(mountpoint -d -q /tmp) == 0:2 ]]; then
      find /tmp -mindepth 1 -xdev -delete && umount /tmp
    fi

    mount -a -t proc
    mount -a -m -t cgroup2,devpts,devtmpfs,sysfs,tmpfs
    mount -m -r -B /run/empty /run/empty
    mkdir -m 1777 -p /run/lock /run/shm

    ln -f -n -s pts/ptmx /dev/ptmx
    ln -f -n -s /proc/self/fd /dev/fd
    ln -f -n -s fd/0 /dev/stdin
    ln -f -n -s fd/1 /dev/stdout
    ln -f -n -s fd/2 /dev/stderr

    if ZRAM=$(zramctl -f -s 1G); then
      mkswap $ZRAM >/dev/null
      swapon -d $ZRAM
    fi

    mount -o remount,ro /
    fsck -a -A -P -T >/dev/null
    if [[ $? -le 1 ]]; then
      mount -o remount,rw /
      mount -a -t nonfs
    fi

    blkid -o device -t PARTLABEL=boot | while read DEVICE; do
      mount -m -r -t vfat -o fmask=0133,nodev,noexec,tz=UTC \
        $DEVICE /boot/${DEVICE#/dev/}
    done

    dmesg --console-off
    while read TTY _; do
      daemon -c -r agetty $TTY
    done < /proc/consoles

    sysctl -q net.core.{r,w}mem_{default,max}=4194304
    sysctl -q net.ipv{4,6}.conf.{all,default}.forwarding=1
    sysctl -q net.ipv4.conf.{all,default}.arp_evict_nocarrier=0
    sysctl -q net.ipv6.conf.{all,default}.ndisc_evict_nocarrier=0
    sysctl -q net.ipv6.conf.eth2.proxy_ndp=1

    sysctl -q net.ipv{4,6}.neigh.default.gc_thresh1=256
    sysctl -q net.ipv{4,6}.neigh.default.gc_thresh2=1024
    sysctl -q net.ipv{4,6}.neigh.default.gc_thresh3=2048

    ip link set lo up
    ip link set eth0 up
    ip link set eth1 up
    ip link set eth2 up
    ip link set eth3 mtu 9000 up

    ip address add 84.45.39.150/30 dev eth0 scope link
    ip address add 2001:9d8:4:15::b/64 dev eth0 preferred_lft 0

    ip address add 194.153.169.172/31 dev eth1 scope link
    ip address add 2001:baf::44:934a/127 dev eth1 preferred_lft 0

    ip address add 91.203.56.10/22 dev eth2
    ip address add 2001:67c:6f0::a/64 dev eth2

    ip address add 91.203.56.1/22 dev eth2
    ip address add 2001:67c:6f0::1/64 dev eth2

    ip address add 10.10.10.20/24 dev eth2 scope link
    ip address add fe80::1/64 dev eth2 scope link

    ip route add default via 84.45.39.149 metric 2048 \
      proto static src 84.45.39.150
    ip route add default via 2001:9d8:4:15::a metric 2048 \
      proto static src 2001:9d8:4:15::b

    if test -w /var/log; then
      syslogd -b
    else
      syslogd -k
    fi

    ueventd -t
    ssh-keygen -A && $(type -P sshd)
    ntpd -p /run/ntpd.pid -s
    bird -P /run/bird.pid

    udpdns -d /etc/microdns -u dns 91.203.56.10 2001:67c:6f0::a
    tcpdns -d /etc/microdns -u dns 91.203.56.10 2001:67c:6f0::a

    daemon "$0" watchdog
    test -w / && daemon "$0" users start

    ctrlaltdel soft
    exec "$0" reap
    ;;

  stop)
    test -w / && "$0" users stop && sleep 3
    kill -TERM -1 && sleep 2 && kill -KILL -1
    echo && dmesg --console-on

    if swapoff -a && umount -a -r; then
      echo "Remounted filesystems read-only"
    elif sync; then
      echo "Flushed filesystem writes"
    fi

    exec stop "${@:2}"
    ;;

  users)
    getent passwd | while IFS=: read -r USER _ _ _ _ HOME SHELL; do
      if [[ -x $HOME/.config/init/${2:-start} ]]; then
        daemon -d "$HOME" -u "$USER" \
          env -i HOME="$HOME" LOGNAME="$USER" PATH="$PATH" SHELL="$SHELL" \
            USER="$USER" "$HOME/.config/init/${2:-start}" "${@:3}"
        logger -p user.info -t init "Spawned $HOME/.config/init/${2:-start}"
      fi
    done
    ;;

  watchdog)
    if [[ -c /dev/watchdog ]]; then
      exec <><(:) >/dev/watchdog && wait
      trap 'printf V && exit' TERM
      while printf '\0'; do read -t 15; done
    fi
    ;;

  *)
    trap 'exec "$0" reap 3>&-' HUP
    trap 'exec "$0" stop reboot 3>&-' INT
    trap 'exec "$0" stop poweroff 3>&-' TERM
    exec 3<><(:) && while true; do read -u 3; done
    ;;
esac
